### ISSUE TITLE
Do not change the default web player

### ISSUE THREAD

**Issue by ghost** [noraworld/videocommander#8]

**Comment by noraworld** [comment]
@sgrjyb I'm sorry that I don't know what you're saying. Could you give us more information?

**Comment by ghost** [comment]
@noraworld Do not replace the player

**Comment by noraworld** [comment]
@sgrjyb Do you want to say the video elements are different between when full screen mode and when not full screen mode?

**Comment by ghost** [comment]
@noraworld Yes

**Comment by noraworld** [comment]
@sgrjyb Well, I have tried two solutions before the current implementation. But I realized both are difficult because of the following reasons.

### 1. Put an upper element of video's one into a full screen element
In some websites like YouTube, a video isn't displayed when entering full screen mode because an upper element has no width or no height. We make an upper element have the same width or height as them of video, then the display gets corrupted.

### 2. Wrap a video element in a element with the same width and height
We need to remember the original size of a video element when entering full screen mode, but a video element and a wrapper are sometimes out of position by this solution.

---

For the above reasons, the solution that we change the HTML position of a video element works best I believe.

I don't intend to change that so far.

**Comment by ghost** [comment]
@noraworld Please try to make a change [HTML5 Video Keyboard Shortcuts](https://chrome.google.com/webstore/detail/html5-video-keyboard-shor/llhmaciggnibnbdokidmbilklceaobae?hl=en)

**Comment by noraworld** [comment]
@sgrjyb Hmm, I don't know what you want me to do.

**Comment by ghost** [comment]
@noraworld Can not refer https://chrome.google.com/webstore/detail/html5-video-keyboard-shor/llhmaciggnibnbdokidmbilklceaobae?hl=en

**Comment by noraworld** [comment]
@sgrjyb I can refer this link, but I don't know what you want to tell me by this link.
